M48
; DRILL file {KiCad 9.0.8-9.0.8~ubuntu22.04.1} date 2026-03-23T17:46:04-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-03-23T17:46:04-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.8-9.0.8~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1200
%
G90
G05
T1
X4.77Y-4.33
X4.9976Y-4.33
T2
X4.866Y-2.8116
M30
